/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SilkJNI */

#ifndef _Included_SilkJNI
#define _Included_SilkJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SilkJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SilkJNI_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     SilkJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SilkJNI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     SilkJNI
 * Method:    createDecoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_SilkJNI_createDecoder
  (JNIEnv *, jclass);

/*
 * Class:     SilkJNI
 * Method:    destroyDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SilkJNI_destroyDecoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SilkJNI
 * Method:    decode
 * Signature: (JI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SilkJNI_decode
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
